openapi: 3.0.0
info:
  title: Documentación de la API
  description: API para gestionar subapartados y posts.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api-docs
paths:
  /subsections:
    get:
      summary: Obtener todos los subapartados
      responses:
        '200':
          description: Lista de subapartados
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        category:
                          type: string
                        description:
                          type: string
                  metadata:
                    type: object
                    properties:
                      total:
                        type: integer
                      count:
                        type: integer
    post:
      summary: Crear un nuevo subapartado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                category:
                  type: string
                description:
                  type: string
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      description:
                        type: string
      responses:
        '201':
          description: Subapartado creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      category:
                        type: string
                      description:
                        type: string
                  message:
                    type: string

  /posts:
    post:
      summary: Crear un nuevo post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                subSection:
                  type: string
      responses:
        '201':
          description: Post creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      content:
                        type: string
                      subSection:
                        type: string
                  message:
                    type: string

    get:
      summary: Obtener posts por subapartado
      parameters:
        - in: path
          name: subSectionId
          required: true
          description: ID del subapartado
          schema:
            type: string
      responses:
        '200':
          description: Lista de posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        content:
                          type: string
                        subSection:
                          type: string

  /login:
    post:
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Credenciales inválidas

  /register:
    post:
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Usuario registrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Solicitud inválida

  /logout:
    get:
      summary: Cerrar sesión
      responses:
        '200':
          description: Cierre de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /profile:
    get:
      summary: Obtener información del perfil del usuario autenticado
      security:
        - bearerAuth: []  # Indica que este endpoint requiere autenticación
      responses:
        '200':
          description: Información del perfil
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
        '401':
          description: No autorizado
