openapi: 3.0.0
info:
  title: Documentación de la API
  description: API para gestionar subapartados, posts y autenticación de usuarios.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor de desarrollo
paths:
  api/auth/register:
    post:
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Usuario registrado exitosamente
        '400':
          description: Solicitud inválida

  api/auth/login:
    post:
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Inicio de sesión exitoso
        '401':
          description: Credenciales inválidas

  api/auth/profile:
    get:
      summary: Obtener información del perfil del usuario autenticado
      security:
        - bearerAuth: []  # Indica que este endpoint requiere autenticación
      responses:
        '200':
          description: Información del perfil
        '401':
          description: No autorizado

  /subsections:
    get:
      summary: Obtener todos los subapartados
      responses:
        '200':
          description: Lista de subapartados
        '404':
          description: No se encontraron subapartados

    post:
      summary: Crear un nuevo subapartado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                category:
                  type: string
                description:
                  type: string
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      description:
                        type: string
      responses:
        '201':
          description: Subapartado creado exitosamente
        '400':
          description: Solicitud inválida

  /posts:
    post:
      summary: Crear un nuevo post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                subSection:
                  type: string
      responses:
        '201':
          description: Post creado exitosamente
        '400':
          description: Solicitud inválida

    get:
      summary: Obtener posts por subapartado
      parameters:
        - in: path
          name: subSectionId
          required: true
          description: ID del subapartado
          schema:
            type: string
      responses:
        '200':
          description: Lista de posts
        '404':
          description: No se encontraron posts

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
